name: 'GitHub Actions Get DL Update Bot'

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: run python
        run: python test.py
        shell: python